const ROLES = {
  ADMIN: 'Admin',
  DEVELOPER: 'Developer',
  TESTER: 'Tester',
};

const ISSUE_STATUS = {
  OPEN: 'Open',
  IN_PROGRESS: 'In Progress',
  TESTING: 'Testing',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
  REOPENED: 'Reopened',
};

const ISSUE_SEVERITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical',
};

const ISSUE_PRIORITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  URGENT: 'Urgent',
};

const PROJECT_STATUS = {
  ACTIVE: 'Active',
  ARCHIVED: 'Archived',
};

const NOTIFICATION_TYPES = {
  ISSUE_ASSIGNED: 'ISSUE_ASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  MENTIONED: 'MENTIONED',
  PROJECT_MEMBERSHIP: 'PROJECT_MEMBERSHIP',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  ISSUE_OVERDUE: 'ISSUE_OVERDUE',
};

const ACTIVITY_ACTIONS = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  ASSIGNED: 'ASSIGNED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  PROJECT_CREATED: 'PROJECT_CREATED',
  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
};

module.exports = {
  ROLES,
  ISSUE_STATUS,
  ISSUE_SEVERITY,
  ISSUE_PRIORITY,
  PROJECT_STATUS,
  NOTIFICATION_TYPES,
  ACTIVITY_ACTIONS,
};