/**
 * @file constants.js
 * @description Centralized enums, statuses, roles, and action types for BugBoard.
 */

const ROLES = {
  ADMIN: 'Admin',
  DEVELOPER: 'Developer',
  TESTER: 'Tester',
};

const PROJECT_STATUS = {
  ACTIVE: 'Active',
  ARCHIVED: 'Archived',
  COMPLETED: 'Completed',
};

const ISSUE_STATUS = {
  OPEN: 'Open',
  IN_PROGRESS: 'In Progress',
  TESTING: 'Testing',
  RESOLVED: 'Resolved',
  CLOSED: 'Closed',
  REOPENED: 'Reopened',
};

const ISSUE_PRIORITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  URGENT: 'Urgent',
};

const ISSUE_SEVERITY = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical',
};

const ACTIVITY_ACTIONS = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  ASSIGNED: 'ASSIGNED',
  COMMENT_ADDED: 'COMMENT_ADDED',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REOPENED: 'REOPENED',
  DELETED: 'DELETED',

  // Aliases referenced by seed scripts and legacy services
  ISSUE_CREATED: 'CREATED',
  ISSUE_UPDATED: 'UPDATED',
  ISSUE_ASSIGNED: 'ASSIGNED',
  ISSUE_RESOLVED: 'RESOLVED',
  ISSUE_CLOSED: 'CLOSED',
  ISSUE_REOPENED: 'REOPENED',
};

const NOTIFICATION_TYPES = {
  ASSIGNED: 'ASSIGNED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  COMMENT: 'COMMENT',
  MENTION: 'MENTION',
  SYSTEM: 'SYSTEM',

  // Aliases
  ISSUE_ASSIGNED: 'ASSIGNED',
  ISSUE_STATUS_CHANGED: 'STATUS_CHANGED',
  ISSUE_COMMENT: 'COMMENT',
  COMMENT_ADDED: 'COMMENT',
};

module.exports = {
  ROLES,
  PROJECT_STATUS,
  STATUS: ISSUE_STATUS,
  ISSUE_STATUS,
  PRIORITY: ISSUE_PRIORITY,
  ISSUE_PRIORITY,
  SEVERITY: ISSUE_SEVERITY,
  ISSUE_SEVERITY,
  ACTIVITY_ACTIONS,
  ACTIVITY_ACTION: ACTIVITY_ACTIONS,
  NOTIFICATION_TYPES,
  NOTIFICATION_TYPE: NOTIFICATION_TYPES,
};